from django.conf.urls import patterns, include, url

urlpatterns = patterns('frontend.views',
	url(r'^video/(?P<id>\d+)$','video',name='video'),
	url(r'^$','index',name='index'),
	url(r'^/$','inicio',name='inicio'),
	url(r'^home/$','home',name='home'),
	url(r'^socios/$','socios',name='socios'),
	url(r'^socio/(?P<dni>\d+)$','socio',name='socio'),
	url(r'^responsabilidad_social/$','responsabilidad_social',name='responsabilidad_social'),
	url(r'^estatutos/$','estatutos',name='estatutos'),
	url(r'^informes/$','informes',name='informes'),
	url(r'^periodismo/$','periodismo',name='periodismo'),
	url(r'^reglamentos/$','reglamentos',name='reglamentos'),
	url(r'^quienes_somos/$','quienes_somos',name='quienes_somos'),
	url(r'^las_noticias/$','las_noticias',name='las_noticias'),
	url(r'^galeria_multimedia/$','galeria_multimedia',name='galeria_multimedia'),
	url(r'^fotos_socios/$','fotos_socios',name='fotos_socios'),
	url(r'^fotos_galeria/$','fotos_galeria',name='fotos_galeria'),
	url(r'^videos_galeria/$','videos_galeria',name='videos_galeria'),

	url(r'^historia/$','historia',name='historia'),
	url(r'^vision_mision/$','vision_mision',name='vision_mision'),
	url(r'^valores/$','valores',name='valores'),

	url(r'^f_junta_directiva/$','f_junta_directiva',name='f_junta_directiva'),
	url(r'^junta_fiscales/$','junta_fiscales',name='junta_fiscales'),
	url(r'^comite_damas/$','comite_damas',name='comite_damas'),

	url(r'^f_carnavales/$','f_carnavales',name='f_carnavales'),
	url(r'^p_28_julio/$','p_28_julio',name='p_28_julio'),
	url(r'^f_patronal/$','f_patronal',name='f_patronal'),
	url(r'^navidad_ninios/$','navidad_ninios',name='navidad_ninios'),
	url(r'^donaciones/$','donaciones',name='donaciones'),
	url(r'^truchada_2013/$','truchada_2013',name='truchada_2013'),
	url(r'^d_navidad_2013/$','d_navidad_2013',name='d_navidad_2013'),
	url(r'^d_escolares/$','d_escolares',name='d_escolares'),
	url(r'^baile_social/$','baile_social',name='baile_social'),
	url(r'^d_navidad_2014/$','d_navidad_2014',name='d_navidad_2014'),

	url(r'^balance_economico/$','balance_economico',name='balance_economico'),
	url(r'^estado_socio/$','estado_socio',name='estado_socio'),
	url(r'^resoluciones/$','resoluciones',name='resoluciones'),
	url(r'^informeT/$','informeT',name='informeT'),
	url(r'^actas/$','actas',name='actas'),
)
