from django.conf.urls import patterns, include, url

urlpatterns = patterns('backend.views',
	url(r'administracion/$','index',name='index'),
	url(r'administracion/junta_directiva/$','junta_directiva',name='junta_directiva'),
    url(r'administracion/$', 'home', name='home'),
    url(r'administracion/temporada$', 'temporada', name='temporada'),
    url(r'administracion/temporada/cierre$', 'cierre_temporada', name='cierre_temporada'),
    url(r'administracion/pagos$', 'ingreso', name='ingreso'),
    url(r'administracion/egresos$', 'egresos', name='egresos'),
    url(r'administracion/perfil/$','perfil',name='perfil'),
    url(r'administracion/galeria_imagenes/$','galeria_imagenes',name='galeria_imagenes'),
    url(r'^administrador/borrar_galeria_imagenes/(?P<id>\d+)$', 'borrar_galeria_imagenes', name='borrar_galeria_imagenes'),
    url(r'^administrador/edit_galeria_imagenes/(?P<id>\d+)$', 'edit_galeria_imagenes', name='edit_galeria_imagenes'),
    url(r'administracion/reporte_socio/$','reporte_socio',name='reporte_socio'),
    url(r'administracion/reporte_socio/(?P<id>\d+)$','reporte_socio',name='reporte_socio'),
    url(r'administracion/reporte_ingresos/$','reporte_ingresos',name='reporte_ingresos'),
    url(r'administracion/reporte_egresos/$','reporte_egresos',name='reporte_egresos'),
    url(r'administracion/reporte_general/$','reporte_general',name='reporte_general'),
    url(r'administracion/galeria_video/$','galeria_video',name='galeria_video'),
)
